-- DOCUMENTS

CREATE TABLE DOCUMENTS (
	Document_ID INT IDENTITY(1, 1) PRIMARY KEY,
	Document_Code VARCHAR(20) NOT NULL UNIQUE,
	Project_ID INT NOT NULL,
	Activity_ID INT NULL,
	Document_Title VARCHAR(200) NOT NULL,
	Document_Type VARCHAR(50),
	Revision VARCHAR(10) NOT NULL DEFAULT 'A',
	File_Path NVARCHAR(500) NULL,
	Uploaded_By VARCHAR(100),
	Uploaded_Date DATE NOT NULL DEFAULT CAST (SYSDATETIME() AS DATE),
	CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
	UpdatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),

	CONSTRAINT fk_documents_project
		FOREIGN KEY (Project_ID) REFERENCES PROJECTS (Project_ID),
	CONSTRAINT fk_documents_activity
		FOREIGN KEY (Activity_ID) REFERENCES WBS_ACTIVITIES (Activity_ID)
);

CREATE INDEX ix_documents_project ON DOCUMENTS (Project_ID);

CREATE INDEX ix_documents_activity ON DOCUMENTS (Activity_ID);