-- VENDORS

CREATE TABLE VENDORS (
	Vendor_ID INT IDENTITY(1, 1) PRIMARY KEY,
	Vendor_Code VARCHAR(20) NOT NULL UNIQUE,
	Vendor_Name VARCHAR(150) NOT NULL,
	Category VARCHAR(50),
	Contact_Person VARCHAR(100),
	Contact_Email VARCHAR(150),
	Contact_Phone VARCHAR(30),
	Country VARCHAR(80),
	CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
	UpdatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);